search_history: 消防厅旁警察厅第二季,消防厅旁警察厅 第二季,命案,命案2023,请回答1988,五十公里桃花坞3,无名女孩,羊毛战记,羊毛战记第一季,孤注一掷
sites:
    - baseurl: https://sdzyapi.com/api.php
      key: 闪电资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://api.xinlangapi.com/xinlangapi.php
      key: 新浪资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://api.guangsuapi.com/api.php
      key: 光速资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://collect.wolongzy.cc/api.php
      key: 卧龙资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://caiji.kczyapi.com/api.php
      key: 快车资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://cj.lziapi.com/api.php
      key: 量子资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://bfzyapi.com/api.php
      key: 暴风资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://suoniapi.com/api.php
      key: 索尼资源
      playurl: ""
      spiderkey: zyw
spider_timeout: 10
