sites:
#    - key: pzdy
#      baseurl: https://pzdy.win
#      playurl: '%s/voddetail/%s.html'
#      spiderkey: maccms
    - key: 闪电资源
      baseurl: https://sdzyapi.com/api.php
      playurl: ''
      spiderkey: zyw
    - key: 新浪资源
      baseurl: https://api.xinlangapi.com/xinlangapi.php
      playurl: ''
      spiderkey: zyw
spider_timeout: 10
