search_history: 夜幕救援,后宫·甄嬛传,吞噬星空,华丽的外出,名侦探柯南：黑铁的鱼影,3D肉蒲团之极乐宝鉴,燃冬,鹊刀门传奇,豆瓣高分国剧！白敬亭一人分饰二角，演技炸裂！明星大侦探衍生剧，目标人物。,美猴王
sites:
    - baseurl: https://sdzyapi.com/api.php
      key: 闪电资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://api.guangsuapi.com/api.php
      key: 光速资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://collect.wolongzy.cc/api.php
      key: 卧龙资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://caiji.kczyapi.com/api.php
      key: 快车资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://cj.lziapi.com/api.php
      key: 量子资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://api.tiankongapi.com/api.php
      key: 天空资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://www.feisuzyapi.com/api.php
      key: 飞速资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://cj.ffzyapi.com/api.php
      key: 非凡资源
      playurl: ""
      spiderkey: zyw
spider_timeout: 10
