sites:
    - key: pzdy
      baseurl: https://pzdy.win
      playurl: '%s/voddetail/%s.html'
      spiderkey: maccms
    - key: pz
      baseurl: https://pzdy.win
      playurl: ""
      spiderkey: ""
