sites:
    - key: pzdy
      baseurl: https://pzdy.win
      playurl: '%s/voddetail/%s.html'
      spiderkey: maccms
    - key: 6080
      baseurl: https://www.6080yy3.com
      playurl: '%s/voddetail/%s.html'
      spiderkey: maccms
spider_timeout: 10
