search_history: ', 长风渡'
sites:
    - baseurl: https://sdzyapi.com/api.php
      key: 闪电资源
      playurl: ""
      spiderkey: zyw
    - baseurl: https://api.xinlangapi.com/xinlangapi.php
      key: 新浪资源
      playurl: ""
      spiderkey: zyw
spider_timeout: 10
